### ISSUE TITLE
only part of drop down list visible

### ISSUE THREAD

**Issue by tamoler** [wbadam/autocomplete-extension#10]
As you can see on the image below only part of drop down list is visible.  
[image](http://i.imgur.com/hB9oZf3.png)

**Comment by wbadam** [comment]
It is perhaps because of the z-index is not being high enough. It is addressed for the next release. Until then try adding css rule similar to
```css
.autocomplete-suggestion-list {
  z-index: 3000;
}
```
